import Image from "next/image";
import type {Metadata} from "next";
import {getPortfolioData} from "@/lib/portfolio";
import {PublicNav,ProjectGallery} from "@/components/public-interactions";
import NeuralBackground from "@/components/neural-background";
export const dynamic="force-dynamic";
export async function generateMetadata():Promise<Metadata>{const{profile}=await getPortfolioData();return{title:profile?.full_name?`${profile.full_name} | ${profile.professional_title}`:"Portfolio",description:profile?.short_intro||"Professional portfolio"}}
export default async function Home(){const{profile,experience,services,projects,certifications}=await getPortfolioData();const sections=["services",...(experience.length?["experience"]:[]),"work",...(certifications.length?["certifications"]:[]),"about","contact"];return <main className="publicPortfolio" id="top"><header className="siteHeader"><PublicNav sections={sections}/></header>
<section className="hero heroFull" aria-labelledby="hero-title"><NeuralBackground/><div className="heroGrid"/><div className="gridGlow"/><div className="sectionGrid"><div className="heroContent"><span className="eyebrow">{profile?.professional_title||"Telecom operations × software"}</span><h1 id="hero-title">I turn complex operations into <em>clear systems.</em></h1><p className="heroCopy">{profile?.short_intro}</p><div className="heroActions"><a className="button primary" href="#work">View my work</a><a className="button secondary" href="#contact">Start a project</a>{profile?.resume_url&&<a className="button quiet" href={profile.resume_url} target="_blank" rel="noopener noreferrer">Résumé ↗</a>}</div></div>{profile?.profile_photo_url&&<div className="profileFrame"><div className="profilePhoto"><Image src={profile.profile_photo_url} alt={profile.profile_photo_alt||`Portrait of ${profile.full_name}`} fill sizes="(max-width:760px) 78vw,350px" priority/></div></div>}</div></section>
{services.length>0&&<section className="publicSection shell" id="services"><Title kicker="What I do" title="Services & Capabilities" copy="Practical technical support across operations, automation, applications, and AI."/><div className="serviceGrid">{services.map(s=><article className="serviceCard" key={s.id}><h3><i/>{s.title}</h3><div className="tags">{s.description.split(/[,\n]/).map(x=>x.trim()).filter(Boolean).map(skill=><span key={skill}>{skill}</span>)}</div></article>)}</div></section>}
{experience.length>0&&<section className="publicSection shell" id="experience"><Title kicker="Career" title="Work Experience"/><div className="timeline">{experience.map(x=><article className="timelineItem" key={x.id}><div><strong>{x.job_title}</strong><span>{x.company}{x.location?` · ${x.location}`:""}</span></div><time>{date(x.start_date)} — {x.is_current?"Present":date(x.end_date)}</time><p>{x.description}</p></article>)}</div></section>}
<section className="publicSection shell" id="work"><Title kicker="Selected work" title="Projects built to solve real problems." copy="Focused tools shaped by real operational needs, from telecom workflows to customer-facing software."/>{projects.length?<ProjectGallery projects={projects}/>:<p className="emptyPublic">New work is coming soon.</p>}</section>
{certifications.length>0&&<section className="publicSection shell" id="certifications"><Title kicker="Credentials" title="Certifications & Technical Training"/><div className="certGrid">{certifications.map(c=><article className={`certCard${c.is_featured?" featured":""}`} key={c.id}><div><i/><div><h3>{c.title}{c.credential_url&&<a href={c.credential_url} target="_blank" rel="noopener noreferrer" aria-label={`Open credential for ${c.title}`}> ↗</a>}</h3><p>{c.issuer}</p></div></div><dl><div><dt>Issued</dt><dd>{date(c.issue_date)}</dd></div>{c.expiration_date&&<div><dt>Expires</dt><dd>{date(c.expiration_date)}</dd></div>}{c.credential_id&&<div><dt>Credential</dt><dd>{c.credential_id}</dd></div>}</dl>{c.description&&<p>{c.description}</p>}<div className="tags">{c.skills.map(s=><span key={s}>{s}</span>)}</div>{c.certificate_file_url&&<a className="certLink" href={c.certificate_file_url} target="_blank" rel="noopener noreferrer">View certificate ↗</a>}</article>)}</div></section>}
{profile&&(profile.about_heading||profile.about_description)&&<section className="publicSection about shell" id="about"><Title kicker="About me" title={profile.about_heading}/><div className="aboutCopy">{profile.about_description.split(/\n\n+/).map((p,i)=><p className={i===0?"lead":""} key={i}>{p}</p>)}</div></section>}
<section className="contact" id="contact"><div className="shell contactGrid"><div><span className="kicker">Get in touch</span><h2>Let&apos;s build something <em>useful.</em></h2><p>Have an operational process, automation, or application in mind? Tell me what needs to work better.</p></div>{profile?.email&&<div className="contactEmailAction"><a className="button primary" href={`mailto:${profile.email}`}>Email me <span aria-hidden="true">↗</span></a></div>}</div></section>
<footer className="footer shell"><div><a className="brand" href="#top">MikRodas</a><p>A telecom operations professional and automation builder in the Philippines. I create practical tools that make teams faster, work clearer, and services more reliable.</p></div><div>{profile?.email&&<a href={`mailto:${profile.email}`}>{profile.email}</a>}{profile?.phone?.trim()&&<a href={`tel:${profile.phone.replace(/[^+\d]/g,"")}`}>{profile.phone}</a>}{profile?.github_url&&<a href={profile.github_url} target="_blank" rel="noopener noreferrer">GitHub ↗</a>}{profile?.linkedin_url&&<a href={profile.linkedin_url} target="_blank" rel="noopener noreferrer">LinkedIn ↗</a>}</div><small>© {new Date().getFullYear()} {profile?.full_name}. All rights reserved.</small></footer></main>}
function Title({kicker,title,copy}:{kicker:string;title:string;copy?:string}){return <div className="sectionTitle"><span className="kicker">{kicker}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
function date(value:string|null){if(!value)return"";return new Intl.DateTimeFormat("en",{month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`))}
